routes/web.php
<?php
/*
 * File name: web.php
 * Last modified: 2021.04.17 at 19:10:17
 * Author: SmarterVision - https://codecanyon.net/user/smartervision
 * Copyright (c) 2021
 */

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\Backoffice\Auth\LoginController;
use App\Http\Controllers\Backoffice\CustomerController;

//Route::get('login/{service}', 'Auth\LoginController@redirectToProvider');
//Route::get('login/{service}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('/', 'Backoffice\Auth\LoginController@pageLogin')->name('login');
Route::get('login', 'Backoffice\Auth\LoginController@pageLogin')->name('login');
Route::get('logout', 'Backoffice\Auth\LoginController@logout')->name('logout');
Route::group(['prefix' => 'backoffice-management-systems', 'as' => 'backoffice-management-systems.'], function () {
    Route::get('login', 'Backoffice\Auth\LoginController@pageLogin')->name('backoffice-management-systems.login');
    Route::post('login', 'Backoffice\Auth\LoginController@login');
    Route::get('logout', 'Backoffice\Auth\LoginController@logout')->name('backoffice-management-systems.logout');

    Route::get('/', 'Backoffice\CustomerController@index');
    Route::resource('customer', 'Backoffice\CustomerController');
    Route::post('customer/deleteDocColData', 'Backoffice\CustomerController@deleteDocColData');
    Route::post('customer/saveDocument', 'Backoffice\CustomerController@saveDocument');
    Route::post('customer/getViewDocCollection', 'Backoffice\CustomerController@getViewDocCollection');
    Route::resource('users', 'Backoffice\UserController');

    Route::get('customer/setting/{id}', 'Backoffice\SettingCustomerController@index');
    Route::post('customer/setting/update', 'Backoffice\SettingCustomerController@store');

});

Route::get('/clear', function() {
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    Artisan::call('route:clear');
    Artisan::call('clear-compiled');
    Artisan::call('config:cache');
    Artisan::call('config:cache');
    Artisan::call('config:clear');
    return '<h1>cleared Success</h1>';
});

//Auth::routes(['verify' => true]);

//Route::get('payments/failed', 'PayPalController@index')->name('payments.failed');
//Route::get('payments/razorpay/checkout', 'RazorPayController@checkout');
//Route::post('payments/razorpay/pay-success/{bookingId}', 'RazorPayController@paySuccess');
//Route::get('payments/razorpay', 'RazorPayController@index');
//
//Route::get('payments/paypal/express-checkout', 'PayPalController@getExpressCheckout')->name('paypal.express-checkout');
//Route::get('payments/paypal/express-checkout-success', 'PayPalController@getExpressCheckoutSuccess');
//Route::get('payments/paypal', 'PayPalController@index')->name('paypal.index');
//
//Route::get('firebase/sw-js', 'AppSettingController@initFirebase');
//
//
//Route::get('storage/app/public/{id}/{conversion}/{filename?}', 'UploadController@storage');
//Route::middleware('auth')->group(function () {
//    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
//    Route::get('/', 'DashboardController@index')->name('dashboard');
//
//    Route::post('uploads/store', 'UploadController@store')->name('medias.create');
//    Route::get('users/profile', 'UserController@profile')->name('users.profile');
//    Route::post('users/remove-media', 'UserController@removeMedia');
//    Route::resource('users', 'UserController');
//    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
//
//    Route::group(['middleware' => ['permission:medias']], function () {
//        Route::get('uploads/all/{collection?}', 'UploadController@all');
//        Route::get('uploads/collectionsNames', 'UploadController@collectionsNames');
//        Route::post('uploads/clear', 'UploadController@clear')->name('medias.delete');
//        Route::get('medias', 'UploadController@index')->name('medias');
//        Route::get('uploads/clear-all', 'UploadController@clearAll');
//    });
//
//    Route::group(['middleware' => ['permission:permissions.index']], function () {
//        Route::get('permissions/role-has-permission', 'PermissionController@roleHasPermission');
//        Route::get('permissions/refresh-permissions', 'PermissionController@refreshPermissions');
//    });
//    Route::group(['middleware' => ['permission:permissions.index']], function () {
//        Route::post('permissions/give-permission-to-role', 'PermissionController@givePermissionToRole');
//        Route::post('permissions/revoke-permission-to-role', 'PermissionController@revokePermissionToRole');
//    });
//
//    Route::group(['middleware' => ['permission:app-settings']], function () {
//        Route::prefix('settings')->group(function () {
//            Route::resource('permissions', 'PermissionController');
//            Route::resource('roles', 'RoleController');
//            Route::resource('customFields', 'CustomFieldController');
//            Route::resource('currencies', 'CurrencyController')->except([
//                'show'
//            ]);
//            Route::resource('taxes', 'TaxController')->except([
//                'show'
//            ]);
//            Route::get('users/login-as-user/{id}', 'UserController@loginAsUser')->name('users.login-as-user');
//            Route::patch('update', 'AppSettingController@update');
//            Route::patch('translate', 'AppSettingController@translate');
//            Route::get('sync-translation', 'AppSettingController@syncTranslation');
//            Route::get('clear-cache', 'AppSettingController@clearCache');
//            Route::get('check-update', 'AppSettingController@checkForUpdates');
//            // disable special character and number in route params
//            Route::get('/{type?}/{tab?}', 'AppSettingController@index')
//                ->where('type', '[A-Za-z]*')->where('tab', '[A-Za-z]*')->name('app-settings');
//        });
//    });
//
//    Route::resource('eProviderTypes', 'EProviderTypeController')->except([
//        'show'
//    ]);
//    Route::post('eProviders/remove-media', 'EProviderController@removeMedia');
//    Route::resource('eProviders', 'EProviderController')->except([
//        'show'
//    ]);
//
//    Route::get('requestedEProviders', 'EProviderController@requestedEProviders')->name('requestedEProviders.index');
//
//    Route::resource('addresses', 'AddressController')->except([
//        'show'
//    ]);
//    Route::resource('awards', 'AwardController');
//    Route::resource('experiences', 'ExperienceController');
//
//    Route::resource('availabilityHours', 'AvailabilityHourController')->except([
//        'show'
//    ]);
//    Route::post('eServices/remove-media', 'EServiceController@removeMedia');
//    Route::resource('eServices', 'EServiceController');
//    Route::resource('faqCategories', 'FaqCategoryController')->except([
//        'show'
//    ]);
//    Route::post('categories/remove-media', 'CategoryController@removeMedia');
//    Route::resource('categories', 'CategoryController')->except([
//        'show'
//    ]);
//    Route::resource('bookingStatuses', 'BookingStatusController')->except([
//        'show',
//    ]);
//    Route::post('galleries/remove-media', 'GalleryController@removeMedia');
//    Route::resource('galleries', 'GalleryController')->except([
//        'show'
//    ]);
//
//
//    Route::resource('eServiceReviews', 'EServiceReviewController')->except([
//        'show'
//    ]);
//    Route::resource('payments', 'PaymentController')->except([
//        'create', 'store', 'edit', 'update', 'destroy'
//    ]);
//    Route::post('paymentMethods/remove-media', 'PaymentMethodController@removeMedia');
//    Route::resource('paymentMethods', 'PaymentMethodController')->except([
//        'show'
//    ]);
//    Route::resource('paymentStatuses', 'PaymentStatusController')->except([
//        'show'
//    ]);
//    Route::resource('faqs', 'FaqController')->except([
//        'show'
//    ]);
//    Route::resource('favorites', 'FavoriteController')->except([
//        'show'
//    ]);
//    Route::resource('notifications', 'NotificationController')->except([
//        'create', 'store', 'update', 'edit',
//    ]);
//    Route::resource('bookings', 'BookingController');
//
//    Route::resource('earnings', 'EarningController')->except([
//        'show', 'edit', 'update'
//    ]);
//
//    Route::get('eProviderPayouts/create/{id}', 'EProviderPayoutController@create')->name('eProviderPayouts.create');
//    Route::resource('eProviderPayouts', 'EProviderPayoutController')->except([
//        'show', 'edit', 'update', 'create'
//    ]);
//    Route::resource('optionGroups', 'OptionGroupController')->except([
//        'show'
//    ]);
//    Route::post('options/remove-media', 'OptionController@removeMedia');
//    Route::resource('options', 'OptionController')->except([
//        'show'
//    ]);
//    Route::resource('coupons', 'CouponController')->except([
//        'show'
//    ]);
//    Route::post('slides/remove-media', 'SlideController@removeMedia');
//    Route::resource('slides', 'SlideController')->except([
//        'show'
//    ]);
//    Route::resource('customPages', 'CustomPageController');
//});

app/Http/Controllers/DashboardController.php
<?php
/*
 * File name: DashboardController.php
 * Last modified: 2021.02.22 at 14:52:03
 * Author: SmarterVision - https://codecanyon.net/user/smartervision
 * Copyright (c) 2021
 */

namespace App\Http\Controllers;

use App\Repositories\BookingRepository;
use App\Repositories\EarningRepository;
use App\Repositories\EProviderRepository;
use App\Repositories\UserRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Response;
use Illuminate\View\View;

class DashboardController extends Controller
{

    /** @var  BookingRepository */
    private $bookingRepository;


    /**
     * @var UserRepository
     */
    private $userRepository;

    /** @var  EProviderRepository */
    private $eProviderRepository;
    /** @var  EarningRepository */
    private $earningRepository;

    public function __construct(BookingRepository $bookingRepo, UserRepository $userRepo, EarningRepository $earningRepository, EProviderRepository $eProviderRepo)
    {
        parent::__construct();
        $this->bookingRepository = $bookingRepo;
        $this->userRepository = $userRepo;
        $this->eProviderRepository = $eProviderRepo;
        $this->earningRepository = $earningRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|Response|View
     */
    public function index()
    {
        $bookingsCount = $this->bookingRepository->count();
        $membersCount = $this->userRepository->count();
        $eprovidersCount = $this->eProviderRepository->count();
        $eProviders = $this->eProviderRepository->limit(4)->get();
        $earning = $this->earningRepository->all()->sum('total_earning');
        $ajaxEarningUrl = route('payments.byMonth', ['api_token' => auth()->user()->api_token]);
//        dd($ajaxEarningUrl);
        return view('dashboard.index')
            ->with("ajaxEarningUrl", $ajaxEarningUrl)
            ->with("bookingsCount", $bookingsCount)
            ->with("eProvidersCount", $eprovidersCount)
            ->with("eProviders", $eProviders)
            ->with("membersCount", $membersCount)
            ->with("earning", $earning);
    }
}

resources/views/dashboard/index.blade.php
@extends('layouts.app')
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header content-header{{setting('fixed_header')}}">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-bold">{{trans('lang.dashboard')}}<small class="mx-3">|</small><small>{{trans('lang.dashboard_overview')}}</small></h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb bg-white float-sm-right rounded-pill px-4 py-2 d-none d-md-flex">
                        <li class="breadcrumb-item"><a href="#"><i class="fas fa-tachometer-alt"></i> {{trans('lang.dashboard')}}</a></li>
                        <li class="breadcrumb-item active">{{trans('lang.dashboard')}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <div class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-white shadow-sm">
                    <div class="inner">
                        <h3 class="text-{{setting('theme_color','primary')}}">{{$bookingsCount}}</h3>

                        <p>{{trans('lang.dashboard_total_bookings')}}</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-calendar-check"></i>
                    </div>
                    <a href="{{route('bookings.index')}}" class="small-box-footer">{{trans('lang.dashboard_more_info')}}
                        <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-white shadow-sm">
                    <div class="inner">
                        @if(setting('currency_right', false) != false)
                            <h3 class="text-{{setting('theme_color','primary')}}">{{$earning}}{{setting('default_currency')}}</h3>
                        @else
                            <h3 class="text-{{setting('theme_color','primary')}}">{{setting('default_currency')}}{{$earning}}</h3>
                        @endif

                        <p>{{trans('lang.dashboard_total_earnings')}} <span style="font-size: 11px">({{trans('lang.dashboard_after taxes')}})</span></p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-hand-holding-usd"></i>
                    </div>
                    <a href="{{route('earnings.index')}}" class="small-box-footer">{{trans('lang.dashboard_more_info')}}
                        <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-white shadow-sm">
                    <div class="inner">
                        <h3 class="text-{{setting('theme_color','primary')}}">{{$eProvidersCount}}</h3>
                        <p>{{trans('lang.e_provider_plural')}}</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-users-cog"></i>
                    </div>
                    <a href="{{route('eProviders.index')}}" class="small-box-footer">{{trans('lang.dashboard_more_info')}}
                        <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-white shadow-sm">
                    <div class="inner">
                        <h3 class="text-{{setting('theme_color','primary')}}">{{$membersCount}}</h3>

                        <p>{{trans('lang.dashboard_total_customers')}}</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-users"></i>
                    </div>
                    <a href="{!! route('users.index') !!}" class="small-box-footer">{{trans('lang.dashboard_more_info')}}
                        <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->

        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-lg-6">
                <div class="card shadow-sm">
                    <div class="card-header no-border">
                        <div class="d-flex justify-content-between">
                            <h3 class="card-title">{{trans('lang.earning_plural')}}</h3>
                            <a href="{{route('payments.index')}}">{{trans('lang.dashboard_view_all_payments')}}</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="d-flex">
                            <p class="d-flex flex-column">
                                @if(setting('currency_right', false) != false)
                                    <span class="text-bold text-lg">{{$earning}}{{setting('default_currency')}}</span>
                                @else
                                    <span class="text-bold text-lg">{{setting('default_currency')}}{{$earning}}</span>
                                @endif
                                <span>{{trans('lang.dashboard_earning_over_time')}}</span>
                            </p>
                            <p class="ml-auto d-flex flex-column text-right">
                                <span class="text-success"> {{$bookingsCount}}</span></span>
                                <span class="text-muted">{{trans('lang.dashboard_total_bookings')}}</span>
                            </p>
                        </div>
                        <!-- /.d-flex -->

                        <div class="position-relative mb-4">
                            <canvas id="sales-chart" height="200"></canvas>
                        </div>

                        <div class="d-flex flex-row justify-content-end">
                            <span class="mr-2"> <i class="fas fa-square text-primary"></i> {{trans('lang.dashboard_this_year')}} </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card shadow-sm">
                    <div class="card-header no-border">
                        <h3 class="card-title">{{trans('lang.e_provider_plural')}}</h3>
                        <div class="card-tools">
                            <a href="{{route('eProviders.index')}}" class="btn btn-tool btn-sm"><i class="fas fa-bars"></i> </a>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <table class="table table-striped table-valign-middle">
                            <thead>
                            <tr>
                                <th>{{trans('lang.e_provider_image')}}</th>
                                <th>{{trans('lang.e_provider')}}</th>
                                <th>{{trans('lang.e_provider_addresses')}}</th>
                                <th>{{trans('lang.actions')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($eProviders as $eProvider)

                                <tr>
                                    <td>
                                        {!! getMediaColumn($eProvider, 'image','img-circle mr-2') !!}
                                    </td>
                                    <td>{!! $eProvider->name !!}</td>
                                    <td>
                                        {!! getArrayColumn($eProvider->addresses,'address') !!}
                                    </td>
                                    <td class="text-center">
                                        <a href="{!! route('eProviders.edit',$eProvider->id) !!}" class="text-muted"> <i class="fas fa-edit"></i> </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('scripts_lib')
    <script src="{{asset('vendor/chart.js/Chart.min.js')}}"></script>
@endpush
@push('scripts')
    <script type="text/javascript">
        var data = [1000, 2000, 3000, 2500, 2700, 2500, 3000];
        var labels = ['JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];

        function renderChart(chartNode, data, labels) {
            var ticksStyle = {
                fontColor: '#495057',
                fontStyle: 'bold'
            };

            var mode = 'index';
            var intersect = true;
            return new Chart(chartNode, {
                type: 'bar',
                data: {
                    labels: labels,
                    datasets: [
                        {
                            backgroundColor: '#007bff',
                            borderColor: '#007bff',
                            data: data
                        }
                    ]
                },
                options: {
                    maintainAspectRatio: false,
                    tooltips: {
                        mode: mode,
                        intersect: intersect
                    },
                    hover: {
                        mode: mode,
                        intersect: intersect
                    },
                    legend: {
                        display: false
                    },
                    scales: {
                        yAxes: [{
                            // display: false,
                            gridLines: {
                                display: true,
                                lineWidth: '4px',
                                color: 'rgba(0, 0, 0, .2)',
                                zeroLineColor: 'transparent'
                            },
                            ticks: $.extend({
                                beginAtZero: true,

                                // Include a dollar sign in the ticks
                                callback: function (value, index, values) {
                                    @if(setting('currency_right', '0') == '0')
                                        return "{{setting('default_currency')}} "+value;
                                    @else
                                        return value+" {{setting('default_currency')}}";
                                    @endif

                                }
                            }, ticksStyle)
                        }],
                        xAxes: [{
                            display: true,
                            gridLines: {
                                display: false
                            },
                            ticks: ticksStyle
                        }]
                    }
                }
            })
        }

        $(function () {
            'use strict'

            var $salesChart = $('#sales-chart')
            $.ajax({
                url: "{!! $ajaxEarningUrl !!}",
                success: function (result) {
                    $("#loadingMessage").html("");
                    var data = result.data[0];
                    var labels = result.data[1];
                    renderChart($salesChart, data, labels)
                },
                error: function (err) {
                    $("#loadingMessage").html("Error");
                }
            });
            //var salesChart = renderChart($salesChart, data, labels);
        })

    </script>
@endpush